In [1]:
# Dependencies
import pandas as pd
import glob

In [3]:
df1 = pd.read_csv('202310-citibike-tripdata.csv')
df1.head()

C:\Users\wambu\AppData\Local\Temp\ipykernel_42376\3845104130.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('202310-citibike-tripdata.csv')

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,F01D2D54E9E60D6E,classic_bike,2023-10-03 02:48:38,2023-10-03 02:48:40,Columbus Pl & Atlantic Ave,4146.02,Columbus Pl & Atlantic Ave,4146.02,40.677223,-73.922792,40.677170,-73.922850,casual
1,CAE4EDBEA07001BD,classic_bike,2023-10-11 16:03:17,2023-10-11 16:45:26,Central Park West & W 85 St,7354.01,Central Park West & W 85 St,7354.01,40.784760,-73.969862,40.784760,-73.969862,casual
2,FDC34BAD31193E07,classic_bike,2023-10-11 19:57:13,2023-10-11 20:20:10,Hicks St & Montague St,4645.09,5 St & 6 Ave,3874.01,40.694974,-73.995936,40.670484,-73.982090,casual
3,DFEA5E65AE91CE2A,classic_bike,2023-10-10 20:18:22,2023-10-10 20:18:37,Atlantic Ave & Furman St,4614.04,Atlantic Ave & Furman St,4614.04,40.691669,-74.000139,40.691652,-73.999979,casual
4,48299D8BE9B55255,classic_bike,2023-10-17 16:26:58,2023-10-17 16:34:27,E 41 St & Madison Ave (SE corner),6432.10,E 58 St & 3 Ave,6762.02,40.751845,-73.979585,40.760958,-73.967245,casual

In [4]:
# Merging csv files (without repeating header)
interesting_files = glob.glob("*.csv") 
df = pd.concat((pd.read_csv(f, header = 0) for f in interesting_files))
df

C:\Users\wambu\AppData\Local\Temp\ipykernel_42376\1479962080.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f, header = 0) for f in interesting_files))
C:\Users\wambu\AppData\Local\Temp\ipykernel_42376\1479962080.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f, header = 0) for f in interesting_files))
C:\Users\wambu\AppData\Local\Temp\ipykernel_42376\1479962080.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f, header = 0) for f in interesting_files))

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C5E94016E7939757,classic_bike,2023-08-29 21:15:27,2023-08-29 21:51:04,Lexington Ave & E 36 St,6313.10,Amsterdam Ave & W 125 St,7800.03,40.747574,-73.978801,40.813358,-73.956461,member
1,E88D94798ABBBD7C,classic_bike,2023-08-06 19:03:35,2023-08-06 19:04:56,Rockaway Ave & Bainbridge St,4285.09,MacDougal St & Rockaway Ave,4212.01,40.683236,-73.911943,40.680180,-73.911360,member
2,341D3CE4743A92EC,classic_bike,2023-08-02 20:34:04,2023-08-02 20:40:19,W 13 St & 5 Ave,5947.04,E 10 St & 2 Ave,5746.02,40.735445,-73.994310,40.729708,-73.986598,member
3,21C763DECA96FD02,classic_bike,2023-08-14 13:47:23,2023-08-14 14:17:36,Central Park North & Adam Clayton Powell Blvd,7617.07,5 Ave & E 29 St,6248.06,40.799484,-73.955613,40.745168,-73.986831,member
4,A8533C28598A6AB8,classic_bike,2023-08-03 13:05:09,2023-08-03 13:52:27,W 13 St & 5 Ave,5947.04,Amsterdam Ave & W 125 St,7800.03,40.735445,-73.994310,40.813358,-73.956461,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3823668,51EEA89890139F57,classic_bike,2023-10-26 08:24:19,2023-10-26 08:30:15,Lewis Ave & Madison St,4425.02,Myrtle Ave & Lewis Ave,4729.01,40.686312,-73.935775,40.696820,-73.937569,member
3823669,439EF43E94F44C88,classic_bike,2023-10-13 11:43:44,2023-10-13 11:52:39,E 44 St & Lexington Ave,6464.09,E 58 St & 3 Ave,6762.02,40.752643,-73.974996,40.760958,-73.967245,member
3823670,A708652F897CA143,classic_bike,2023-10-19 16:37:15,2023-10-19 16:45:47,8 Ave & W 38 St,6526.05,W 48 St & Rockefeller Plaza,6626.11,40.754646,-73.991850,40.757769,-73.979294,casual
3823671,42E855EBB9F79B8E,classic_bike,2023-10-19 17:50:36,2023-10-19 18:01:55,8 Ave & W 38 St,6526.05,W 56 St & 6 Ave,6809.07,40.754610,-73.991770,40.763406,-73.977225,casual
3823672,B0E02662944E86C9,classic_bike,2023-10-19 15:33:27,2023-10-19 15:55:14,Riverside Dr & W 78 St,7340.06,Amsterdam Ave & W 79 St,7311.02,40.784021,-73.983778,40.782939,-73.978652,casual

In [5]:
# List of file names to be combined 
files32023 = ['202308-citibike-tripdata.csv', '202309-citibike-tripdata.csv', '202310-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df32023_list = []

# Loop through each file in the list
for file in files32023:
    # Read the file into a dataframe
    df32023 = pd.read_csv(file)

    # Append the dataframe to the list
    df32023_list.append(df32023)

# Concatenate all dataframes in the list into one dataframe
df32023 = pd.concat(df32023_list)

# Show dataframe
df32023

C:\Users\wambu\AppData\Local\Temp\ipykernel_42376\3504781756.py:10: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df32023 = pd.read_csv(file)
C:\Users\wambu\AppData\Local\Temp\ipykernel_42376\3504781756.py:10: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df32023 = pd.read_csv(file)
C:\Users\wambu\AppData\Local\Temp\ipykernel_42376\3504781756.py:10: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df32023 = pd.read_csv(file)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C5E94016E7939757,classic_bike,2023-08-29 21:15:27,2023-08-29 21:51:04,Lexington Ave & E 36 St,6313.10,Amsterdam Ave & W 125 St,7800.03,40.747574,-73.978801,40.813358,-73.956461,member
1,E88D94798ABBBD7C,classic_bike,2023-08-06 19:03:35,2023-08-06 19:04:56,Rockaway Ave & Bainbridge St,4285.09,MacDougal St & Rockaway Ave,4212.01,40.683236,-73.911943,40.680180,-73.911360,member
2,341D3CE4743A92EC,classic_bike,2023-08-02 20:34:04,2023-08-02 20:40:19,W 13 St & 5 Ave,5947.04,E 10 St & 2 Ave,5746.02,40.735445,-73.994310,40.729708,-73.986598,member
3,21C763DECA96FD02,classic_bike,2023-08-14 13:47:23,2023-08-14 14:17:36,Central Park North & Adam Clayton Powell Blvd,7617.07,5 Ave & E 29 St,6248.06,40.799484,-73.955613,40.745168,-73.986831,member
4,A8533C28598A6AB8,classic_bike,2023-08-03 13:05:09,2023-08-03 13:52:27,W 13 St & 5 Ave,5947.04,Amsterdam Ave & W 125 St,7800.03,40.735445,-73.994310,40.813358,-73.956461,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3823668,51EEA89890139F57,classic_bike,2023-10-26 08:24:19,2023-10-26 08:30:15,Lewis Ave & Madison St,4425.02,Myrtle Ave & Lewis Ave,4729.01,40.686312,-73.935775,40.696820,-73.937569,member
3823669,439EF43E94F44C88,classic_bike,2023-10-13 11:43:44,2023-10-13 11:52:39,E 44 St & Lexington Ave,6464.09,E 58 St & 3 Ave,6762.02,40.752643,-73.974996,40.760958,-73.967245,member
3823670,A708652F897CA143,classic_bike,2023-10-19 16:37:15,2023-10-19 16:45:47,8 Ave & W 38 St,6526.05,W 48 St & Rockefeller Plaza,6626.11,40.754646,-73.991850,40.757769,-73.979294,casual
3823671,42E855EBB9F79B8E,classic_bike,2023-10-19 17:50:36,2023-10-19 18:01:55,8 Ave & W 38 St,6526.05,W 56 St & 6 Ave,6809.07,40.754610,-73.991770,40.763406,-73.977225,casual
3823672,B0E02662944E86C9,classic_bike,2023-10-19 15:33:27,2023-10-19 15:55:14,Riverside Dr & W 78 St,7340.06,Amsterdam Ave & W 79 St,7311.02,40.784021,-73.983778,40.782939,-73.978652,casual

In [6]:
# Save the dataframe to a CSV file
df32023.to_csv('citibike.csv', index=False)

In [7]:
df32023.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C5E94016E7939757,classic_bike,2023-08-29 21:15:27,2023-08-29 21:51:04,Lexington Ave & E 36 St,6313.10,Amsterdam Ave & W 125 St,7800.03,40.747574,-73.978801,40.813358,-73.956461,member
1,E88D94798ABBBD7C,classic_bike,2023-08-06 19:03:35,2023-08-06 19:04:56,Rockaway Ave & Bainbridge St,4285.09,MacDougal St & Rockaway Ave,4212.01,40.683236,-73.911943,40.680180,-73.911360,member
2,341D3CE4743A92EC,classic_bike,2023-08-02 20:34:04,2023-08-02 20:40:19,W 13 St & 5 Ave,5947.04,E 10 St & 2 Ave,5746.02,40.735445,-73.994310,40.729708,-73.986598,member
3,21C763DECA96FD02,classic_bike,2023-08-14 13:47:23,2023-08-14 14:17:36,Central Park North & Adam Clayton Powell Blvd,7617.07,5 Ave & E 29 St,6248.06,40.799484,-73.955613,40.745168,-73.986831,member
4,A8533C28598A6AB8,classic_bike,2023-08-03 13:05:09,2023-08-03 13:52:27,W 13 St & 5 Ave,5947.04,Amsterdam Ave & W 125 St,7800.03,40.735445,-73.994310,40.813358,-73.956461,member

In [8]:
df32023.shape

(11492004, 13)

In [9]:
df32023.count

<bound method DataFrame.count of                   ride_id rideable_type           started_at  \
0        C5E94016E7939757  classic_bike  2023-08-29 21:15:27
1        E88D94798ABBBD7C  classic_bike  2023-08-06 19:03:35
2        341D3CE4743A92EC  classic_bike  2023-08-02 20:34:04
3        21C763DECA96FD02  classic_bike  2023-08-14 13:47:23
4        A8533C28598A6AB8  classic_bike  2023-08-03 13:05:09
...                   ...           ...                  ...
3823668  51EEA89890139F57  classic_bike  2023-10-26 08:24:19
3823669  439EF43E94F44C88  classic_bike  2023-10-13 11:43:44
3823670  A708652F897CA143  classic_bike  2023-10-19 16:37:15
3823671  42E855EBB9F79B8E  classic_bike  2023-10-19 17:50:36
3823672  B0E02662944E86C9  classic_bike  2023-10-19 15:33:27

                    ended_at                             start_station_name  \
0        2023-08-29 21:51:04                        Lexington Ave & E 36 St
1        2023-08-06 19:04:56                   Rockaway Ave & Bainbridge St
2        2023-08-02 20:40:19                                W 13 St & 5 Ave
3        2023-08-14 14:17:36  Central Park North & Adam Clayton Powell Blvd
4        2023-08-03 13:52:27                                W 13 St & 5 Ave
...                      ...                                            ...
3823668  2023-10-26 08:30:15                         Lewis Ave & Madison St
3823669  2023-10-13 11:52:39                        E 44 St & Lexington Ave
3823670  2023-10-19 16:45:47                                8 Ave & W 38 St
3823671  2023-10-19 18:01:55                                8 Ave & W 38 St
3823672  2023-10-19 15:55:14                         Riverside Dr & W 78 St

        start_station_id              end_station_name end_station_id  \
0                6313.10      Amsterdam Ave & W 125 St        7800.03
1                4285.09   MacDougal St & Rockaway Ave        4212.01
2                5947.04               E 10 St & 2 Ave        5746.02
3                7617.07               5 Ave & E 29 St        6248.06
4                5947.04      Amsterdam Ave & W 125 St        7800.03
...                  ...                           ...            ...
3823668          4425.02        Myrtle Ave & Lewis Ave        4729.01
3823669          6464.09               E 58 St & 3 Ave        6762.02
3823670          6526.05  W 48 St &  Rockefeller Plaza        6626.11
3823671          6526.05               W 56 St & 6 Ave        6809.07
3823672          7340.06       Amsterdam Ave & W 79 St        7311.02

         start_lat  start_lng    end_lat    end_lng member_casual
0        40.747574 -73.978801  40.813358 -73.956461        member
1        40.683236 -73.911943  40.680180 -73.911360        member
2        40.735445 -73.994310  40.729708 -73.986598        member
3        40.799484 -73.955613  40.745168 -73.986831        member
4        40.735445 -73.994310  40.813358 -73.956461        member
...            ...        ...        ...        ...           ...
3823668  40.686312 -73.935775  40.696820 -73.937569        member
3823669  40.752643 -73.974996  40.760958 -73.967245        member
3823670  40.754646 -73.991850  40.757769 -73.979294        casual
3823671  40.754610 -73.991770  40.763406 -73.977225        casual
3823672  40.784021 -73.983778  40.782939 -73.978652        casual

[11492004 rows x 13 columns]>

In [10]:
df32023.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object